base_url = "https://www.maeevick.com/"

default_language = "en"

minify_html = true
compile_sass = true

[markdown]
highlight_code = true
external_links_target_blank = true

[extra]

[languages.fr]
title = "Maeevick"
description = "Mon petit univers presque créatif où fantasy, expérimentations tech et développement de jeux prenent vie ou explosent."

[languages.en]
title = "Maeevick"
description = "My almost creative little universe where fantasy, tech experiments, and game development live and explode."


