name: Build and Deploy Zola Website

on:
  push:
    paths:
      - "app/**"
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: app
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
